name: Build ONNX Runtime for Inference

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-onnx-runtime:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2025
            platform: windows-x64
            shell: cmd
          - os: windows-11-arm
            platform: windows-arm64
            shell: cmd
          - os: ubuntu-22.04
            platform: linux-x64
            shell: bash
          - os: ubuntu-22.04-arm
            platform: linux-arm64
            shell: bash
          - os: ubuntu-22.04
            platform: android
            shell: bash
          - os: macos-15
            platform: macos
            sdk: macosx
            shell: bash
          - os: macos-15
            platform: ios
            sdk: iphoneos
            shell: bash
          - os: macos-15
            platform: ios-simulator
            sdk: iphonesimulator
            shell: bash
      fail-fast: false
    steps:
      - name: Checkout ONNX Runtime
        uses: actions/checkout@v4
        with:
          repository: Microsoft/onnxruntime
          ref: v1.21.1
          submodules: recursive

      - name: Setup Python - All Platforms
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup CMake - Windows (x64/arm64) / Linux (x64) / macOS (x64/arm64) / iOS / Android
        if: matrix.platform != 'linux-arm64'
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.1'

      - name: Install CMake - Linux (arm64)
        if: matrix.platform == 'linux-arm64'
        run: |
          python3 -m pip install cmake==4.0.0
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Setup Xcode and Setup Command Line Tools - macOS/iOS
        if: matrix.platform == 'macos' || matrix.platform == 'ios' || matrix.platform == 'ios-simulator'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3.0'

      - name: Determine SDK Path and set SDKROOT - macOS/iOS
        if: matrix.platform == 'macos' || matrix.platform == 'ios' || matrix.platform == 'ios-simulator'
        run: |
          sdk="${{ matrix.sdk }}"
          SDKROOT=$(xcrun --sdk $sdk --show-sdk-path)
          echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV
          echo "Using SDK: $sdk"
        shell: bash

      - name: Setup Java - Android
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Setup Android SDK/NDK - Android
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-36 ndk;27.2.12479018'
          accept-android-sdk-licenses: true

      - name: Build ONNX Runtime - Windows (x64)
        if: matrix.platform == 'windows-x64'
        run: .\build.bat --config Release --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --update --build
        shell: cmd

      - name: Build ONNX Runtime - Windows (arm64)
        if: matrix.platform == 'windows-arm64'
        run: .\build.bat --config Release --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --update --build
        shell: cmd

      - name: Build ONNX Runtime - Linux (x64)
        if: matrix.platform == 'linux-x64'
        run: |
          ./build.sh --config Release --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --update --build
        shell: bash

      - name: Build ONNX Runtime - Linux (arm64)
        if: matrix.platform == 'linux-arm64'
        run: ./build.sh --config Release --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --update --build
        shell: bash

      - name: Build ONNX Runtime - Android (arm64-v8a / armeabi-v7a)
        if: matrix.platform == 'android'
        run: |
          # Android arm64-v8a
          ./build.sh --config Release --android --android_sdk_path $ANDROID_SDK_ROOT --android_ndk_path $ANDROID_NDK_ROOT --android_abi arm64-v8a --android_api 24 --skip_submodule_sync
          # Android armeabi-v7a
          ./build.sh --config Release --android --android_sdk_path $ANDROID_SDK_ROOT --android_ndk_path $ANDROID_NDK_ROOT --android_abi armeabi-v7a --android_api 24 --skip_submodule_sync
        shell: bash

      - name: Build ONNX Runtime - macOS (x86_64 / arm64)
        if: matrix.platform == 'macos'
        run: |
          # macOS fat binary (x86_64 + arm64)
          ./build.sh --config Release --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --apple_deploy_target 11.0 --cmake_extra_defines CMAKE_OSX_ARCHITECTURES="x86_64;arm64" --update --build
        shell: bash

      - name: Build ONNX Runtime - iOS Device (arm64)
        if: matrix.platform == 'ios'
        run: |
          ./build.sh --config Release --use_xcode --ios --apple_sysroot iphoneos --osx_arch arm64 --apple_deploy_target 13.0 --skip_submodule_sync
        shell: bash

      - name: Build ONNX Runtime - iOS Simulator (x86_64)
        if: matrix.platform == 'ios-simulator'
        run: |
          ./build.sh --config Release --use_xcode --ios --apple_sysroot iphonesimulator --osx_arch x86_64 --apple_deploy_target 13.0 --skip_submodule_sync
        shell: bash

      - name: List and inspect output libraries (Windows)
        if: startsWith(matrix.platform, 'windows')
        shell: pwsh
        run: |
          Write-Host "====== Listing native libraries (.dll/.lib) ======"
          Get-ChildItem -Recurse -Include *.dll, *.lib -Path . | ForEach-Object {
            Write-Host "Found: $($_.FullName)"
            if ($_.Extension -eq '.dll') {
              Write-Host "Running dumpbin for: $($_.FullName)"
              $dumpbin = Get-Command "dumpbin.exe" -ErrorAction SilentlyContinue
              if ($dumpbin) {
                & $dumpbin /DEPENDENTS $_.FullName 2>&1 | Write-Host
              } else {
                Write-Host "dumpbin.exe not found in PATH"
              }
            }
          }
          Write-Host "====== End of listing ======"

      - name: List and inspect output libraries (Unix)
        if: matrix.platform != 'windows-arm64' && matrix.platform != 'windows-x64'
        shell: bash
        run: |
          echo "====== Listing native libraries (.so/.a/.dylib) ======"
          find . -type f \( -iname "*.so" -o -iname "*.a" -o -iname "*.dylib" \) -print | while read file; do
            echo "Found: $file"
            if command -v ldd &> /dev/null; then
              echo "Dependencies for $file:"
              ldd "$file" || true
            elif command -v otool &> /dev/null; then
              echo "Dependencies for $file:"
              otool -L "$file" || true
            fi
          done
          echo "====== End of listing ======"